spring:
  application:
    name: kyc-batch-postal-codes
  profiles:
    active: dev
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never
      table-prefix: KYC_BATCH_

kyc-messages:
  catalog:
    messages:
      "001":
        code: KYC-BATCH-POSTAL-CODES-001
        message: Unexpected Error
        type: ERROR
      "002":
        code: KYC-BATCH-POSTAL-CODES-002
        message: The file content is invalid
        type: ERROR
